
# Climate change component


## *Problem definition*

1. Human-induced climate change is a problem that will require a united, global effort to combat. However, the effects of climate change do and will continue to affect Forrest at a community level. Such affects include increasing temperatures, drying climates, increased and more serious bushfires, droughts, and more extreme weather. To remain safe and stay resilient in the face of climate change, Forrest must anticipate more frequent bushfires, flooding and drought, and develop plans for sustainable recovery.

*Dynamic hypothesis:*

Forrest is vulnerable to bushfires and drought, and the effect of climate change on biodiversity may begin to affect Forrest’s eco-tourism economy. Increasing temperatures will also affect Forrest’s residents, especially as the community is ageing. More frequent heatwaves will put older people, more susceptible to heat-induced illness, at risk. Forrest is occasionally subject to flooding (e.g. the spillover of Barwon Dam in 2012), and with the increase in extreme weather events this could become more frequent.


## *System conceptualisation*

There are four climate-related models that make up the climate change component, with a separate structure for cultural burning. These four models are for carbon dioxide, temperature, rainfall, and bushfire.  

## *Model formulation*

For each of the four climate models, we generated linear models based on past data. The rainfall model is for annual rainfall; the temperature model is for annual mean maximum temperature; the CO~2~ model is for monthly CO~2~ measurements; and for bushfire we modelled the annual mean Forest Fire Danger Index (@matthews_comparison_2009) for the Forrest area. The linear models were created using data from 1990-2020.  

The climate damage structure was adapted from FeliX (@rydzak_impact_2010).  

The cultural burning structure represents the percentage of land that is managed by cultural burning. The initial value is 0 and the model is 'switched' on or off depending on scenario. The cultural burning goal is set as 100%.


## Data sources  

Data and code are available at [https://github.com/pelagikat/Local-SDGs-systems-model](https://github.com/pelagikat/Local-SDGs-systems-model)  

CO~2~ data was obtained from the [Cape Grim monitoring station](https://www.csiro.au/en/research/natural-environment/atmosphere/latest-greenhouse-gas-data)  

Temperature and rainfall data was obtained from the [Bureau of Meteorology](http://www.bom.gov.au/climate/data/?ref=ftr). Temperature data was from the Cape Otway weather station, and rainfall data was from the Pennyroyal weather station. These stations were selected as they were both the most complete and spatially nearest datasets available.  

Forest Fire Danger Index historical data was provided from the Victorian Government Department of Land, Water and Planning ViCClim dataset. Data was extracted from the spatial VicClim dataset using the centre of Forrest township. We do not have permission to share this data.  


## Abbreviations

FFDI = Forest Fire Danger Index  

***

## *Equations*

### annual probability of flood  

Type: Constant  
Formula: 0.01  
Units: Dmnl  
Assumptions: Corangamite Catchment Management Authority [flood mapping portal](https://www.ccmaknowledgebase.vic.gov.au/flood/cb_pages/flood_mapping.php) shows 1 in 100 year riverine flood extent (limited data)  
    
### bushfire risk fraction  

Type: Auxiliary  
Formula: reference FFDI/FFDI model  
Units: Dmnl  
Assumptions: Modelled FFDI at time of simulation as proportion of reference FFDI  

### climate damage fraction  

Type: Auxiliary  
Formula: 1 / ( 1 + climate damage scale * (temperature change since 1865 / reference temperature for climate damages ) ^ climate damage nonlinearity)  
Units: Dmnl  
Assumptions: Variable and formula taken from FeliX (@rydzak_impact_2010). Fraction of Output lost to combating Climate Change.  

### climate damage nonlinearity  

Type: Constant  
Formula: 2  
Units: Dmnl  
Assumptions: Variable and formula taken from FeliX (@rydzak_impact_2010). Nonlinearity (exponent) of Climate Damage Cost Fraction.  

### climate damage scale  

Type: Constant  
Formula: 0.013  
Units: Dmnl  
Assumptions: Variable and formula taken from FeliX (@rydzak_impact_2010). Coefficient for climate damage fraction at Reference Temperature.  

### CO2 change  

Type: Auxiliary  
Formula: CO2 linear model - reference CO2  
Units: ppm  
Assumptions: Change from reference CO2 value  

### CO2 linear model  

Type: Auxiliary  
Formula: CO2 model coefficient * Time - 3177.44  
Units: ppm  
Assumptions: Model derived from data. See code and data in Github.  

### CO2 model coefficient  

Type: Constant  
Formula: 1.77  
Units: ppm/Year  
Assumptions: Model derived from data. See code and data in Github.  

### Cultural Burning  

Type: Stock  
Formula: INTEG (Cultural burning rate), INITIAL = 0  
Units: Dmnl  
Assumptions:  

### cultural burning adjustment time  

Type: Constant  
Formula: 15  
Units: Year  
Assumptions: Victorian Cultural Fire Strategy (@the_victorian_traditional_owner_cultural_fire_knowledge_group_victorian_2021) states a 10 year transition time to properly implement cultural burning, as Country is currently too sick to immediately begin cultural burns. We assume an additional 5 years to implement the strategy.  

### cultural burning discrepancy  

Type: Auxiliary  
Formula: cultural burning goal - Cultural Burning  
Units: Dmnl  
Assumptions: The difference between the goal and the current state  

### cultural burning goal  

Type: Constant  
Formula: 1  
Units: Dmnl  
Assumptions: The goal is to have 100% of land managed by cultural burning  

### Cultural burning rate  

Type: Auxiliary  
Formula: IF THEN ELSE ( Time < 2025, 0, (cultural burning discrepancy / cultural burning adjustment time) * cultural burning scenario switch)  
Units: 1/Year  
Assumptions: Assume that cultural burning won't commence until 2025  

### cultural burning scenario switch  

Type: Constant  
Formula: 0  
Units: Dmnl  
Assumptions: The scenario switch variable. 0 = off, 1 = on.  

### FFDI model  

Type: Auxiliary  
Formula: (FFDI model coefficient * Time) - 51.7397  
Units: Dmnl  
Assumptions: linear model of FFDI dataset from 1990-2020. Model derived from data. See code and data in Github.  

### FFDI model coefficient  

Type: Constant  
Formula: 0.02662  
Units: 1/Year  
Assumptions: Coefficient of linear model of FFDI dataset 1990-2020  

### net climate change impact on economy  

Type: Auxiliary  
Formula: climate damage fraction  
Units: Dmnl  
Assumptions: Variable and formula taken from FeliX (@rydzak_impact_2010). The fraction of ecomomy output loss due to climate change.  

### rainfall change  

Type: Auxiliary  
Formula: rainfall linear model - reference rainfall  
Units: mm  
Assumptions: Change from reference rainfall value.  

### rainfall linear model  

Type: Auxiliary  
Formula: (rainfall model coefficient * Time) + 6182.65  
Units: mm  
Assumptions: linear model for data 1990-2020 for Pennyroyal weather station. Model derived from data. See code and data in Github.  

### rainfall model coefficient  

Type: Constant  
Formula: -2.711  
Units: mm/Year  
Assumptions: Coefficient of linear model of annual rainfall 1990-2020 using Pennyroyal weather station data  

### reference CO2  

Type: Constant  
Formula: 348.33  
Units: ppm  
Assumptions: CO2 mean Cape Grim data for 1976-2000. See code and data in Github.  

### reference FFDI  

Type: Constant  
Formula: 1.4  
Units: Dmnl  
Assumptions: 1973 annual mean FFDI.  

### reference rainfall  

Type: Constant  
Formula: 776  
Units: mm  
Assumptions: Pennyroyal rainfall measuring station; mean of annual rainfall 1960-2020. See code and data in Github.  

### reference temperature 1865  

Type: Constant  
Formula: 16.6  
Units: DegreesC  
Assumptions: Annual mean max temperature. Earliest available full year dataset for Cape Otway climate station. See data in Github.

### reference temperature for climate damages  

Type: Constant  
Formula: 3  
Units: DegreesC  
Assumptions: Reference Temperature change for Calculation of Climate Damages. Variable and formula taken from FeliX (@rydzak_impact_2010).  

### temperature change since 1865  

Type: Auxiliary  
Formula: temperature linear model - reference temperature 1865  
Units: DegreesC  
Assumptions:  

### temperature linear model  

Type: Auxiliary  
Formula: (temperature model coefficient * Time) - 47.88  
Units: DegreesC  
Assumptions: linear model for Annual mean max temp 1990-2020 for Cape Otway weather station. Model derived from data. See code and data in Github.  

### temperature model coefficient  

Type: Constant  
Formula: 0.03241  
Units: DegreesC/Year  
Coefficient of linear model of Cape Otway annual mean max temperatures from 1990-2020. Model derived from data. See code and data in Github.  
