
# Health and Wellbeing component


## *Problem definition*
1. Being in a regional area, Forrest does not have local access to healthcare services (closest hospital is Colac). 

*Dynamic hypothesis:*
Living in regional areas impacts life expectancy.

2. Potential disease burden in Forrest has been estimated to be approximately 80-90,000 times greater than the WHO target because of failing septic systems in Forrest.

*Dynamic hypothesis:*
Building new wastewater infrastructure will reduce disease burden

3. Climate change and bushfire are risks to the local environment and population.

*Dynamic hypothesis:*
People like to live in Forrest because the local bush has a positive effect on wellbeing but there is a trade-off from bushfire risk

4. There is a wide income distribution in Forrest, with a larger proportion of people in lower income brackets compared to the state.

*Dynamic hypothesis:*
People experiencing income inequality have poorer health outcomes (social gradient of health)


## *System conceptualisation*

This component was inspired by the work of @homer_system_2006, and seeks to model local scale population health contributors. The community clearly identified positive and negative impacts on health and wellbeing, many of which are modelled in other components in the local SDG systems model.


### Conceptual model
```{r, echo = FALSE, warning = FALSE, dev='png', fig.width=15 }
library(DiagrammeR)

grViz("
digraph {
  graph[layout = dot, rankdir = LR]
  node[shape = box, fontname = Arial]
  'Safer healthier people'; 'Vulnerable people'

  node[shape = oval, fontname = Arial]
  'Biodiversity'; 'Higher income'; 'Bushfire safety'; 'Water quality'; 'Wastewater disease burden';
  'Healthcare access'; 'Climate risk'; 'Lower income'; 'Road accidents'; 'Disability'

  # edge statements
  'Safer healthier people'->'Vulnerable people' 'Vulnerable people'->'Safer healthier people'
  'Wastewater disease burden'->'Vulnerable people' 'Healthcare access'->'Vulnerable people'
  'Climate risk'->'Vulnerable people' 'Lower income'->'Vulnerable people' 'Road accidents'->'Vulnerable people'
  'Disability'->'Vulnerable people' 'Water quality'->'Vulnerable people'
   'Biodiversity'->'Safer healthier people' 'Higher income'->'Safer healthier people'
  'Bushfire safety'->'Safer healthier people'
 
}
")
```

## *Model formulation*

Following the model in Figure 3 of @homer_system_2006, this component models "Safer healthier people" and "Vulnerable people" as stocks, and these form a cycle with flow variables. The various different health impacts (normalised where required) are multiplied together in the flow variables and this creates the dynamics of the model component.

## Data sources

Data are available at [https://github.com/pelagikat/Local-SDGs-systems-model](https://github.com/pelagikat/Local-SDGs-systems-model)

Data was obtained from the [Victorian Government DATA VIC](https://discover.data.vic.gov.au/dataset/crash-stats-data-extract) for road accident statistics.

Census data for Forrest available [here.](https://www.abs.gov.au/websitedbs/D3310114.nsf/Home/2016%20QuickStats) Data for Forrest as a distinct location is only available for 2006, 2011 and 2016 censuses.

## Abbreviations
GTOC = Gateway to the Otways Centre, a Bushfire Safer Place  
WHO = World Health Organisation  
WW = Wastewater, new local wastewater infrastructure  

*** 

## *Equations*

### accident coefficient

Type: Constant  
Formula: -19.25  
Units: people  
Assumptions: Calibrated against road accident data. See Github for data.  

### Becoming safer and healthier  

Type: Auxiliary  
Formula: (increasing bushfire safety from GTOC * ( biodiversity impact on health (middle and high income population / total population) * total population) / Time)  
Units: people/Year  
Assumptions:  

### Becoming vulnerable  

Type: Auxiliary  
Formula: (( climate risk * disability fraction * water quality * disease from wastewater * excess disease burden from lowered healthcare access * (low income population / total population) * (road accidents / total population)) * total population) / Time  
Units: people/Year  
Assumptions: 

### biodiversity impact on health  

Type: Auxiliary  
Formula: Species richness / INIT species richness  
Units: Dmnl  
Assumptions: Current species richness as a proportion of the baseline species richness  

### climate risk  

Type: Auxiliary  
Formula: risk to health from bushfire * risk to health from increasing temperatures  
Units: Dmnl  
Assumptions: the main risks to health as a result of climate are bushfire and high temperature  

### disease burden before WW  

Type: Constant  
Formula: 0.1  
Units: Year/person  
Assumptions: Wastewater investigation report in Forrest (@decentralised_water_consulting_forrest_2019, p. 28) found that the existing disease burden was approximately $1 \times 10^{-1}$ (or 0.1) Disability Adjusted Life Years (DALYs). Note the @decentralised_water_consulting_forrest_2019 report calls this "Level of Disease Protection" instead of disease burden, and appears to incorrectly interpret Figure 12 in the text.  

### disease from wastewater  

Type: Auxiliary  
Formula: (IF THEN ELSE ( Wastewater availability > 0, WHO target disease burden / WHO target disease burden, disease burden before WW / WHO target disease burden))  
Units: Dmnl  
Assumptions: Effect of installing new wastewater infrastructure as a proportion of the WHO target.  

### excess disease burden from lowered healthcare access  

Type: Constant  
Formula: 1.103  
Units: fraction  
Assumptions: Forrest is classified as inner regional by the [RRMA classification](https://www.health.gov.au/health-topics/health-workforce/health-workforce-classifications/rural-remote-and-metropolitan-area). Inner regional areas have 10.3% excess disease burden compared to major cities (percentage of total observed burden for the area) (@australian_institute_of_health_and_welfare_australian_2019, Table 8.5)  

### high income population  

Type: Auxiliary  
Formula: sum ( number labour force in income bracket[high income!,Gender!])  
Units: people  
Assumptions: Summed over income cohorts $1,500 and above, and summed over gender  

### increasing bushfire safety from GTOC  

Type: Auxiliary  
Formula: IF THEN ELSE ( GTOC availability > 0, 1-bushfire risk fraction, 1)  
Units: Dmnl  
Assumptions: If GTOC has been built, its presence negates the risk from bushfire as it is a Bushfire Safer Place  

### low income population  

Type: Auxiliary  
Formula: sum ( number labour force in income bracket[low income!, Gender!])  
Units: people  
Assumptions: Summed over income cohorts from Negative to $649, and summed over gender.  

### middle and high income population  

Type: Auxiliary  
Formula: high income population + middle income population  
Units: people  
Assumptions:   

### middle income population  

Type: Auxiliary  
Formula: sum ( number labour force in income bracket[mid income!,Gender!])  
Units: people  
Assumptions: Summed over income cohorts from $650 - $1,499, and summed over gender.  

### population initial  

Type: Constant  
Formula: 171  
Units: people  
Assumptions: From 2006 census data, population at start of simulation.  

### risk to health from bushfire  

Type: Auxiliary  
Formula: bushfire risk fraction  
Units: Dmnl  
Assumptions: A one-to-one mapping of bushfire risk fraction  

### risk to health from increasing temperatures  

Type: Auxiliary  
Formula: climate damage fraction  
Units: Dmnl  
Assumptions: A one-to-one mapping of climate damage fraction  

### road accidents  

Type: Auxiliary  
Formula: Road Quality * accident coefficient + 9.6  
Units: people  
Assumptions: Linear model calibrated in Vensim. Intercept is dataset mean.  

### Safer Healthier People

Type: Stock  
Formula: INTEG (Becoming safer and healthier - Becoming vulnerable), INITIAL = population initial  
Units: people  
Assumptions: There are only two states of being in this model: Safer & Healthier, or Vulnerable.  

### Vulnerable People

Type: Stock  
Formula: INTEG (Becoming vulnerable - Becoming safer and healthier), INITIAL = 0)  
Units: people  
Assumptions: There are only two states of being in this model: Safer & Healthier, or Vulnerable. Assume that all the population begin as Safer & Healthier and as the simulation runs, may move to Vulnerable.  

### water quality  

Type: Constant  
Formula: 1  
Units: Dmnl  
Assumptions: This is a scenario variable. The baseline is zero (no effect).  

### WHO target disease burden  

Type: Constant  
Formula: 1e-05  
Units: Year/person  
Assumptions: Wastewater investigation report in Forrest (@decentralised_water_consulting_forrest_2019, p. 28) states that the World Health Organisation target disease burden from wastewater was approximately $1 \times 10^{-5}$ Disability Adjusted Life Years (DALYs). Note the @decentralised_water_consulting_forrest_2019 report calls this "Level of Disease Protection" instead of disease burden, and appears to incorrectly interpret Figure 12 in the text. The new wastewater infrastructure will meet this disease burden target.  
