---
title: "Climate change component documentation"
author: "Katrina Szetey"
date: "03/02/2022"
bibliography: CC.bib
output: html_document
---

# Climate change overview


## *Problem definition*

1. Human-induced climate change is a problem that will require a united, global effort to combat. However, the effects of climate change do and will continue to affect Forrest at a community level. Such affects include increasing temperatures, drying climates, increased and more serious bushfires, droughts, and more extreme weather. To remain safe and stay resilient in the face of climate change, Forrest must anticipate more frequent bushfires, flooding and drought, and develop plans for sustainable recovery.

*Dynamic hypothesis:*

Forrest is vulnerable to bushfires and drought, and the effect of climate change on biodiversity may begin to affect Forrest’s eco-tourism economy. Increasing temperatures will also affect Forrest’s residents, especially as the community is ageing. More frequent heatwaves will put older people, more susceptible to heat-induced illness, at risk. Forrest is occasionally subject to flooding (e.g. the spillover of Barwon Dam in 2012), and with the increase in extreme weather events this could become more frequent.


## *System conceptualisation*

There are four climate-related models that make up the climate change component, with a separate structure for cultural burning. These four models are for carbon dioxide, temperature, rainfall, and bushfire.  

## *Model formulation*

For each of the four climate models, we generated linear models based on past data. The rainfall model is for annual rainfall; the temperature model is for annual mean maximum temperature; the CO~2~ model is for monthly CO~2~ measurements; and for bushfire we modelled the annual mean Forest Fire Danger Index (@matthews_comparison_2009) for the Forrest area.   

The cultural burning structure represents the percentage of land that is managed by cultural burning. The initial value is 0 and the model is 'switched' on or off depending on scenario. The cultural burning goal is set as 100%.


## Data sources  

Data and code are available at [https://github.com/pelagikat/Local-SDGs-systems-model](https://github.com/pelagikat/Local-SDGs-systems-model)  

CO~2~ data was obtained from the [Cape Grim monitoring station](https://www.csiro.au/en/research/natural-environment/atmosphere/latest-greenhouse-gas-data)  

Temperature and rainfall data was obtained from the [Bureau of Meteorology](http://www.bom.gov.au/climate/data/?ref=ftr). Temperature data was from the Cape Otway weather station, and rainfall data was from the Pennyroyal weather station. These stations were selected as they were both the most complete and spatially nearest datasets available.  

Forest Fire Danger Index historical data was provided from the Victorian Government Department of Land, Water and Planning ViCClim dataset. Data was extracted from the spatial VicClim dataset using the centre of Forrest township. We do not have permission to share this data.  


## Abbreviations

FFDI = Forest Fire Danger Index  

***

## *Equations*

### annual probability of flood  

Type: Constant  
Formula: 0.01  
Units: Dmnl  
Assumptions: Corangamite Catchment Management Authority [flood mapping portal](https://www.ccmaknowledgebase.vic.gov.au/flood/cb_pages/flood_mapping.php) shows 1 in 100 year riverine flood extent (limited data)  
    
### bushfire risk fraction  

Type: Auxiliary  
Formula: reference FFDI/FFDI model  
Units: Dmnl  
Assumptions: Modelled FFDI at time of simulation as proportion of reference FFDI  

climate damage fraction=
    1/(1+climate damage scale*(temperature change since 1865/reference temperature for climate damages
)^climate damage nonlinearity)
Units: Dmnl
Fraction of Output lost to combating Climate Change.

climate damage nonlinearity=
    2
Units: Dmnl
Nonlinearity of Climate Damage Cost Fraction.

climate damage scale=
    0.013
Units: Dmnl
Climate Damage Fraction at Reference Temperature.

CO2 change=
    CO2 linear model-reference CO2
Units: ppm

CO2 linear model=
    CO2 model coefficient*Time - 3177.44
Units: ppm
Cape Grim data modelled y-intercept -3177.44

CO2 model coefficient=
    1.77
Units: ppm/Year
Cape Grim linear model of CO2 increase

Cultural Burning= INTEG (
    Cultural burning rate,
        0)
Units: Dmnl

cultural burning adjustment time=
    15
Units: Year
Victorian Cultural Fire Strategy states a 10 year transition 
        time to properly implement cultural burning, as Country is 
        currently too sick to immediatly begin cultural burns. We assume 
        an additional 5 years to implement the strategy.

cultural burning discrepancy=
    cultural burning goal-Cultural Burning
Units: Dmnl

cultural burning goal=
    1
Units: Dmnl
The goal is to have 100% of land managed by cultural burning

Cultural burning rate=
    IF THEN ELSE(Time < 2025, 0, (cultural burning discrepancy/cultural burning adjustment time
)*cultural burning scenario switch)
Units: 1/Year
Assume that cultural burning won't commence until 2025

cultural burning scenario switch=
    0
Units: Dmnl

FFDI model=
    (FFDI model coefficient*Time) - 51.7397
Units: Dmnl
linear model of FFDI dataset from 1990-2020

FFDI model coefficient=
     0.02662
Units: 1/Year
Coefficient of linear model of FFDI dataset 1990-2020

net climate change impact on economy=
    climate damage fraction
Units: Dmnl
The fraction of ecomomy output loss due to climate change.

rainfall change=
    rainfall linear model-reference rainfall
Units: mm

rainfall linear model=
    (rainfall model coefficient*Time)+ 6182.65
Units: mm
Intercept calculated from linear model for data 1990-2020 for 
        Pennyroyal weather station

rainfall model coefficient=
    -2.711
Units: mm/Year
Coefficient of linear model of annual rainfall since 1990 using 
        Pennyroyal weather station data

reference CO2=
    348.33
Units: ppm
CO2 mean Cape Grim data for 1976-2000

reference FFDI=
    1.4
Units: Dmnl
FFDI as at 1973; first year of data for linear model

reference rainfall=
    776
Units: mm
Pennyroyal rainfall measuring station; mean of annual rainfall 
        1960-2020

reference temperature 1865=
    16.6
Units: DegreesC
Earliest available full year dataset for Cape Otway climate 
        station

reference temperature for climate damages=
    3
Units: DegreesC
Reference Temperature for Calculation of Climate Damages.

temperature change since 1865=
    temperature linear model-reference temperature 1865
Units: DegreesC

temperature linear model=
    (temperature model coefficient*Time)-47.88
Units: DegreesC
Modelled intercept of equation = -47.87707

temperature model coefficient=
    0.03241
Units: DegreesC/Year
Coefficient of linear model of Cape Otway annual mean 
        temperatures from 1990-2020



## References
