---
title: "Health and wellbeing component documentation"
author: "Katrina Szetey"
date: "02/02/2022"
output: html_document
---

# Health and Wellbeing overview


## *Problem definition*
1. Being in a regional area, Forrest does not have local access to healthcare services (closest hospital is Colac). 

*Dynamic hypothesis:*
Living in regional areas impacts life expectancy.

2. Potential disease burden in Forrest has been estimated to be approximately 80-90,000 times greater than the WHO target because of failing septic systems in Forrest.

*Dynamic hypothesis:*
Building new wastewater infrastructure will reduce disease burden

3. Climate change and bushfire are risks to the local environment and population.

*Dynamic hypothesis:*
People like to live in Forrest because the local bush has a positive effect on wellbeing but there is a trade-off from bushfire risk

4. There is a wide income distribution in Forrest, with a larger proportion of people in lower income brackets compared to the state.

*Dynamic hypothesis:*
People experiencing income inequality have poorer health outcomes (social gradient of health)


## *System conceptualisation*


### Conceptual model
```{r, echo = FALSE, warning = FALSE}
library(DiagrammeR)

grViz("
digraph {
  graph[layout = dot, rankdir = LR]
  node[shape = box, fontname = Arial]
  'Safer healthier people'; 'Vulnerable people'

  node[shape = oval, fontname = Arial]
  'Biodiversity'; 'Higher income'; 'Bushfire safety'; 'Water quality'; 'Wastewater disease burden';
  'Healthcare access'; 'Climate risk'; 'Lower income'; 'Road accidents'; 'Disability'

  # edge statements
  'Safer healthier people'->'Vulnerable people' 'Vulnerable people'->'Safer healthier people'
  'Wastewater disease burden'->'Vulnerable people' 'Healthcare access'->'Vulnerable people'
  'Climate risk'->'Vulnerable people' 'Lower income'->'Vulnerable people' 'Road accidents'->'Vulnerable people'
  'Disability'->'Vulnerable people' 'Water quality'->'Vulnerable people'
   'Biodiversity'->'Safer healthier people' 'Higher income'->'Safer healthier people'
  'Bushfire safety'->'Safer healthier people'
 
}
")
```




## *Model formulation*


*** 

## *Equations*

accident coefficient=
        -19.25
    Units: people
    Calibrated

Becoming safer and healthier=
    (increasing bushfire safety from GTOC*(biodiversity impact on health*
    (middle and high income population/total population)*
    total population)/
    Time)
Units: people/Year

Becoming vulnerable=
    ((climate risk*
    disability fraction*
    water quality*
    disease from wastewater*
    excess disease burden from lowered healthcare access*
    (low income population/total population)*
    (road accidents/total population))*
    total population)/
    Time
Units: people/Year

biodiversity impact on health=
    Species richness/INIT species richness
Units: Dmnl

bushfire risk fraction=
    reference FFDI/FFDI model
Units: Dmnl

climate damage fraction=
    1/(1+climate damage scale*(temperature change since 1865/reference temperature for climate damages
)^climate damage nonlinearity)
Units: Dmnl
Fraction of Output lost to combating Climate Change.

climate risk=
    risk to health from bushfire*risk to health from increasing temperatures
Units: Dmnl

disability fraction=
    0.177
Units: Dmnl
https://www.abs.gov.au/statistics/health/disability/disability-ag
        eing-and-carers-australia-summary-findings/2018 Percentage of 
        population who have a disability

disease burden before WW=
    0.1
Units: Year/person
Data from Forrest Wastewater Investigation report

disease from wastewater=
    (IF THEN ELSE(Wastewater availability > 0, WHO target disease burden/WHO target disease burden
, disease burden before WW/WHO target disease burden))
Units: Dmnl
Effect of installing new wastewater infrastructure as a 
        proportion of the WHO target.

excess disease burden from lowered healthcare access=
    1.103
Units: fraction
Forrest is classified as inner regional by the RRMA 
        classification 
        https://www.health.gov.au/health-topics/health-workforce/health-w
        orkforce-classifications/rural-remote-and-metropolitan-area 
        Inner regional areas have 10.3% excess disease burden compared 
        to major cities (percentage of total observed burden for the 
        area). 
        https://www.aihw.gov.au/getmedia/c076f42f-61ea-4348-9c0a-d996353e
        838f/aihw-bod-22.pdf.aspx?inline=true Table 8.5

GTOC availability=
    IF THEN ELSE(time at which GTOC is complete>0, STEP(1, (Current time + time at which GTOC is complete
)) , 0 )
Units: Year

high income population=
    sum(number labour force in income bracket[high income!,Gender!])
Units: people

increasing bushfire safety from GTOC=
    IF THEN ELSE(GTOC availability>0, 1-bushfire risk fraction, 1)
Units: Dmnl

INIT species richness=
    4637
Units: species
Baseline 1990 data for species richness in the Colac Otway LGA 
        area. Includes amphibians, birds, mammals, plants and reptiles.

low income population=
    sum(number labour force in income bracket[low income!, Gender!])
Units: people

middle and high income population=
    high income population+middle income population
Units: people

middle income population=
    sum(number labour force in income bracket[mid income!,Gender!])
Units: people

number labour force in income bracket[Income,Gender]=
    INTEGER(income distribution fractions by income cohort and gender[Income,Gender
]*labour force[Gender])
Units: people

population initial=
    231
Units: people
From 2016 Census data

risk to health from bushfire=
    bushfire risk fraction
Units: Dmnl

risk to health from increasing temperatures=
    climate damage fraction
Units: Dmnl

road accidents=
    Road Quality*accident coefficient + 9.6
Units: people
Intercept is dataset mean

Road Quality= INTEG (
    Road maintenance rate-Road deterioration rate,
        0)
Units: Dmnl

Safer Healthier People= INTEG (
    Becoming safer and healthier-Becoming vulnerable,
        population initial)
Units: people

Species richness= INTEG (
    Species richness increase rate-Species richness decrease rate,
        INIT species richness)
Units: species

total population=
    "0-14" + "15-64" + "65+"
Units: people

Vulnerable People= INTEG (
    Becoming vulnerable-Becoming safer and healthier,
        0)
Units: people

Wastewater availability=
    IF THEN ELSE(time at which Wastewater is complete > 0, STEP(1, (Current time
 + time at which Wastewater is complete)) , 0 )
Units: Year
The time from which the wastewater infrastructure is complete 
        and can begin having an effect on other variables

water quality=
    1
Units: Dmnl
Scenario variable. Baseline zero.

WHO target disease burden=
    1e-05
Units: Year/person
The new wastewater infrastructure will meet this disease burden 
        target

