---
title: "Infrastructure component documentation"
author: "Katrina Szetey"
date: "02/02/2022"
output: html_document
---

# Infrastructure Overview

The Forrest community have four major infrastructure projects currently in train which they have identified as being important for the future development and growth of Forrest. There is one additional project which is as important for the community but not reliant on outside intervention.

## *Problem definition*
1. In the past, on-site septic systems were adequate for a town the size of Forrest, which did not have many visitors. With the change to a tourism economy, there are many more people that come to town, particularly for events, and the now ageing septic infrastructure requires upgrading. The limits of septic infrastructure for waste are hindering attempts to increase housing in the town. Studies have been undertaken by Barwon Water to upgrade wastewater infrastructure but there has been no progress, partly due to funding issues. The current option on the table expects the community to contribute, which may delay or entirely derail the development.

*Dynamic hypothesis:*
Ageing septic systems that don’t meet current safety standards are no longer adequate and new infrastructure is urgently needed. This affects the local environment and biodiversity, the local economy (by limiting tourism), health of local residents, and additional development in the town.

2. The Forrest MTB Trails were first opened in 2005, encompassing over 60km of trails. A proposal was released in December 2019 to increase the MTB trail network by approximately 38kms, including restructuring the existing trails and creating a new Trail Head. This plan is aimed to revitalise mountain bike tourism and re-establish Forrest as a nationally significant mountain bike destination.

*Dynamic hypothesis:*
Mountain bike trails in Forrest are already a major tourism drawcard but upgrades to the trail network would encourage more visitation to the town. This is a benefit to the tourism economy but issues still remain around accommodation (i.e. housing supply) and wastewater.

3. The Forrest Common is a piece of public land which could be put to better use for the community. After several years of consultation with Colac Otway Shire, a plan has been approved but it is beyond the ability of Council to fund.

*Dynamic hypothesis:*
A revamped Forrest Common would benefit tourism and in-migration of families (due to new play equipment).

4. The community identified that a bushfire safer place is necessary for the community, and that one of the DELWP parcels of land could be used to achieve this. A feasibility study and preliminary plans have been completed, but funding needs to be found to build it.

*Dynamic hypothesis:*
If funding can be obtained for the Gateway to The Otways Centre, this would have a positive impact on community health and wellbeing in the event of a bushfire and potentially prevent loss of life.



## *System conceptualisation*


### Conceptual model
```{r, echo = FALSE, warning = FALSE}
library(DiagrammeR)

grViz("
digraph {
  graph[layout = dot, rankdir = LR]
  node[shape = box, fontname = Arial]
  'Funding'; 'Build in progress'; 'Completed infrastructure'

  node[shape = oval, fontname = Arial]
  'Time delay'

  # edge statements
  'Funding'->'Build in progress' 'Build in progress'->'Completed infrastructure'
  'Time delay'->'Funding' 'Time delay'->'Build in progress'
 
}
")

```




## *Model formulation*


***

## *Equations*



## Second CFA Truck

The community are raising funds for the CFA truck themselves so it is not reliant on outside funding. Thus it is not dependent on the funding scenarios and funding allocation rate. 

### Unit cost of CFA truck

Type: constant  
Formula: 350,000  
Units: dollar/asset component  
Assumption: one new CFA truck costs $350,000.  <p style="background-color:yellow;">Clarifying with Pete/Emma Ashton.</p>

### Second CFA truck funding

Type: constant  
Formula: 350,000  
Units: dollars/year  
Assumption: It will take 1 year to raise all the money required. <p style="background-color:yellow;">Clarifying with Pete/Emma Ashton.</p> 

### second CFA truck funding lag

Type: constant  
Formula: 1  
Units: years  
Assumption: It will take 1 year to raise all the money required  

### second CFA truck build delay

Type: constant  
Formula: 0.5  
Units: years  
Assumption: It will take 0.5 years from ordering to delivery (ie build time)  

### Second CFA truck construction rate

Type: rate  
Formula: DELAY1( second CFA truck funding/unit cost of CFA truck, second CFA truck build delay+second CFA truck funding lag)  
Units: asset component/year  
Assumption: The input is the number of asset components per year, the delay is the funding lag plus the build delay  

***

## Gateway to the Otways Centre

The community want to use the former DELWP land on Grant St to build a new, state-of-the-art bushfire place of last resort. This building would also become a multi-purpose community centre and possibly have some function for tourism or conference facilities.  


### GTOC funding approved

Type: auxilliary
Formula: IF THEN ELSE(funding scenario=1, 1.2e+07 , 0 )  
Units: dollars  
Assumption: The cost of building GTOC is $12,000,000  

### Gateway to the Otways Centre Funding

Type: stock  
Formula: INTEG(-GTOC funding allocation rate, GTOC funding approved)  
Units: dollars  
Assumption:   

### GTOC funding duration

Type: constant  
Formula: 2  
Units: years  
Assumption: The funding will continue for the same time as the build time  

### GTOC funding allocation rate

Type: Rate  
Formula: Gateway to the Otways Centre Funding/GTOC funding duration  
Units: dollars/year  
Assumption: The project is fully funded


### unit cost of GTOC

Type: constant
Formula: 1,200,000   
Units: dollars per asset component  
Assumption: Have arbitrarily assumed that the GTOC has 10 asset components (or 'build stages')  


***
New stuff after here

asset component discrepancy CFA Truck=
        total number of asset components CFA Truck- Completed CFA Truck
    Units: asset component
    
asset component discrepancy Forrest Common=
    total number of asset components Forrest Common- Completed Forrest Common
Units: asset component

asset component discrepancy GTOC=
    total number of asset components GTOC- Completed GTOC
Units: asset component

asset component discrepancy MTB Trails=
    total number of asset components MTB Trails- Completed MTB Trails
Units: asset component

asset component discrepancy Wastewater=
    total number of asset components Wastewater- Completed Wastewater
Units: asset component

build delay CFA Truck=
    0.5
Units: Year

build delay Forrest Common=
    0.5
Units: Year

build delay GTOC=
    1
Units: Year

build delay MTB Trails=
    1
Units: Year

build delay Wastewater=
    2
Units: Year

build time CFA Truck=
    0.25
Units: Year

build time Forrest Common=
    0.5
Units: Year

build time GTOC=
    2
Units: Year

build time MTB Trails=
    1
Units: Year

build time Wastewater=
    3
Units: Year

CFA Truck approved funding=
    IF THEN ELSE ( funding scenario CFA Truck
                      = 1, 
                 21000, 
                 0)
Units: dollar
Confirmed CFA truck $ with Pete Ashton

CFA Truck availability=
    IF THEN ELSE(time at which CFA Truck is complete>0, STEP(1, (Current time 
+ time at which CFA Truck is complete)) , 0 )
Units: Year

CFA Truck Build In Progress= INTEG (
    CFA Truck start rate-CFA Truck completion rate,
        0)
Units: asset component

CFA Truck completion rate =
    (asset component discrepancy CFA Truck)/build time CFA Truck
Units: asset component/Year

CFA Truck Funding = INTEG (
    -CFA Truck funding allocation rate,
        CFA Truck approved funding)
Units: dollar

CFA Truck funding allocation rate=
    CFA Truck Funding/CFA Truck funding duration
Units: dollar/Year

CFA Truck funding duration=
    1
Units: Year

CFA Truck start rate=
    DELAY1 ( CFA Truck funding allocation rate/cost per asset component CFA Truck
, build delay CFA Truck + funding lag CFA Truck)
Units: asset component/Year

Completed CFA Truck= INTEG (
    CFA Truck completion rate,
        0)
Units: asset component

Completed Forrest Common= INTEG (
    Forrest Common completion rate,
        0)
Units: asset component

Completed GTOC= INTEG (
    GTOC completion rate,
        0)
Units: asset component

Completed MTB Trails= INTEG (
    MTB Trails completion rate,
        0)
Units: asset component

Completed Wastewater= INTEG (
    Wastewater completion rate,
        0)
Units: asset component

cost per asset component CFA Truck=
    210000/10
Units: dollar/asset component

cost per asset component Forrest Common=
    1.7e+06
                 / 10
Units: dollar/asset component

cost per asset component GTOC=
    ( 1.2e+07) 
                 / 10
Units: dollar/asset component

cost per asset component MTB Trails=
    4.55e+06
                 / 10
Units: dollar/asset component

cost per asset component Wastewater=
    1.01e+07
                 / 10
Units: dollar/asset component

Current time=
    2021
Units: Year

Forrest Common approved funding=
    IF THEN ELSE ( Forrest Common funding scenario
                      = 1, 
                 1.7e+06, 
                 0)
Units: dollar
Confirmed CFA truck $ with Pete Ashton

Forrest Common availability=
    IF THEN ELSE(time at which Forrest Common is complete>0, STEP(1, (Current time
+ time at which Forrest Common is complete
    )) , 0 )
Units: Year

Forrest Common Build In Progress= INTEG (
    Forrest Common start rate-Forrest Common completion rate,
        0)
Units: asset component

Forrest Common completion rate=
    (asset component discrepancy Forrest Common)/build time Forrest Common
Units: asset component/Year

Forrest Common Funding= INTEG (
    -Forrest Common funding allocation rate,
        Forrest Common approved funding)
Units: dollar

Forrest Common funding allocation rate=
    Forrest Common Funding/Forrest Common funding duration
Units: dollar/Year

Forrest Common funding duration=
    1
Units: Year

Forrest Common funding scenario=
    0
Units: Dmnl

Forrest Common start rate=
    DELAY1 ( Forrest Common funding allocation rate/cost per asset component Forrest Common
, build delay Forrest Common + funding lag Forrest Common)
Units: asset component/Year

funding lag CFA Truck=
    1
Units: Year

funding lag Forrest Common=
    2
Units: Year

funding lag GTOC=
    5
Units: Year

funding lag MTB Trails=
    0.5
Units: Year

funding lag Wastewater=
    2
Units: Year

funding scenario CFA Truck=
    0
Units: Dmnl

GTOC approved funding=
    IF THEN ELSE ( GTOC funding scenario
                      = 1, 
                 1.2e+07, 
                 0)
Units: dollar
Confirmed CFA truck $ with Pete Ashton

GTOC availability=
    IF THEN ELSE(time at which GTOC is complete>0, STEP(1, (Current time + time at which GTOC is complete
)) , 0 )
Units: Year

GTOC Build In Progress= INTEG (
    GTOC start rate-GTOC completion rate,
        0)
Units: asset component

GTOC completion rate=
    (asset component discrepancy GTOC)/build time GTOC
Units: asset component/Year

GTOC Funding= INTEG (
    -GTOC funding allocation rate,
        GTOC approved funding)
Units: dollar

GTOC funding allocation rate=
    GTOC Funding/GTOC funding duration
Units: dollar/Year

GTOC funding duration=
    2
Units: Year

GTOC funding scenario=
    0
Units: Dmnl

GTOC start rate=
    DELAY1 ( GTOC funding allocation rate/cost per asset component GTOC, build delay GTOC
 + funding lag GTOC)
Units: asset component/Year

MTB Trails approved funding=
    IF THEN ELSE ( MTB Trails funding scenario
                      = 1, 
                 4.55e+06, 
                 0)
Units: dollar
Confirmed CFA truck $ with Pete Ashton

MTB Trails Build In Progress= INTEG (
    MTB Trails start rate-MTB Trails completion rate,
        0)
Units: asset component

MTB Trails completion rate=
    (asset component discrepancy MTB Trails)/build time MTB Trails
Units: asset component/Year

MTB Trails Funding= INTEG (
    -MTB Trails funding allocation rate,
        MTB Trails approved funding)
Units: dollar

MTB Trails funding allocation rate=
    MTB Trails Funding/MTB Trails funding duration
Units: dollar/Year

MTB Trails funding duration=
    1
Units: Year

MTB Trails funding scenario=
    1
Units: Dmnl

MTB trails improvements availability=
    IF THEN ELSE(time at which MTB Trails is complete>0, STEP(1, (Current time
 + time at which MTB Trails is complete)) , 0 )
Units: Year

MTB Trails start rate=
    DELAY1 ( MTB Trails funding allocation rate/cost per asset component MTB Trails
, build delay MTB Trails + funding lag MTB Trails)
Units: asset component/Year

time at which CFA Truck is complete=
    IF THEN ELSE(funding scenario CFA Truck > 0, build delay CFA Truck+build time CFA Truck
+funding lag CFA Truck , 0 )
Units: Year

time at which Forrest Common is complete=
    IF THEN ELSE(Forrest Common funding scenario > 0, build delay Forrest Common
+build time Forrest Common+funding lag Forrest Common , 0 )
Units: Year

time at which GTOC is complete=
    IF THEN ELSE(GTOC funding scenario > 0, build delay GTOC+build time GTOC+funding lag GTOC
 , 0 )
Units: Year

time at which MTB Trails is complete=
    IF THEN ELSE(MTB Trails funding scenario > 0, build delay MTB Trails+build time MTB Trails
+funding lag MTB Trails , 0 )
Units: Year

time at which Wastewater is complete=
    IF THEN ELSE(Wastewater funding scenario > 0, build delay Wastewater+build time Wastewater
+funding lag Wastewater, 0)
Units: Year

total number of asset components CFA Truck=
    10
Units: asset component

total number of asset components Forrest Common=
    10
Units: asset component

total number of asset components GTOC=
    10
Units: asset component

total number of asset components MTB Trails=
    10
Units: asset component

total number of asset components Wastewater=
    10
Units: asset component

Wastewater approved funding=
    IF THEN ELSE ( Wastewater funding scenario
                      = 1, 
                 1.01e+07, 
                 0)
Units: dollar
Confirmed CFA truck $ with Pete Ashton

Wastewater availability=
    IF THEN ELSE(time at which Wastewater is complete > 0, STEP(1, (Current time
 + time at which Wastewater is complete)) , 0 )
Units: Year
The time from which the wastewater infrastructure is complete 
        and can begin having an effect on other variables

Wastewater Build In Progress= INTEG (
    Wastewater start rate-Wastewater completion rate,
        0)
Units: asset component

Wastewater completion rate=
    (asset component discrepancy Wastewater)/build time Wastewater
Units: asset component/Year

Wastewater Funding= INTEG (
    -Wastewater funding allocation rate,
        Wastewater approved funding)
Units: dollar

Wastewater funding allocation rate =
    Wastewater Funding/Wastewater funding duration
Units: dollar/Year

Wastewater funding duration=
    3
Units: Year

Wastewater funding scenario=
    0
Units: Dmnl

Wastewater start rate=
    DELAY1 ( Wastewater funding allocation rate/cost per asset component Wastewater
, build delay Wastewater + funding lag Wastewater)
Units: asset component/Year



